FROM openjdk:11.0

COPY target/fundmanager-0.0.1-SNAPSHOT.jar /app.jar

RUN sh -c 'echo spring.datasource.url=jdbc:mysql://mysql:3306/manager?serverTimezone=UTC&useSSL=false > application-prod.properties'
RUN sh -c 'echo spring.datasource.username=root >> application-prod.properties'
RUN sh -c 'echo spring.datasource.password=C0nygre-C0nygre >> application-prod.properties'

CMD ["Sleep 240 && java -jar /app.jar"]
#ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "/app.jar"]

EXPOSE 8080
